/**
 * @distilled.cloud/acp — Agent Client Protocol (ACP) client SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy model in
 * `.generated-specs` (written by `scripts/convert.ts` from ACP's JSON
 * Schema). Everything else in this folder is hand-written.
 *
 * Outbound calls to the agent are typed operations (`Acp.initialize`,
 * `Acp.sessionNew`, `Acp.sessionPrompt`, `Acp.sessionCancel`, …); the
 * agent's `session/update` notifications are the `Acp.sessionUpdates`
 * stream; the agent's callbacks into the client are typed handlers passed to
 * the connection layer.
 *
 * @example
 * ```ts
 * import * as NodeServices from "@effect/platform-node/NodeServices";
 * import { Effect, Layer } from "effect";
 * import * as Acp from "@distilled.cloud/acp";
 *
 * const program = Effect.gen(function* () {
 *   yield* Acp.initialize({ protocolVersion: Acp.ACP_PROTOCOL_VERSION });
 *   const { sessionId } = yield* Acp.sessionNew({ cwd: process.cwd(), mcpServers: [] });
 *   return sessionId;
 * });
 *
 * program.pipe(
 *   Effect.provide(
 *     Acp.layerChildProcess({ command: "opencode", args: ["acp"] }).pipe(
 *       Layer.provide(NodeServices.layer),
 *     ),
 *   ),
 *   Effect.runPromise,
 * );
 * ```
 */
export * from "./services/acp.ts";
export * from "./errors.ts";
export * as T from "./traits.ts";
export { ACP_PROTOCOL_VERSION, AcpConnection, AcpProtocol, type AcpOpError } from "./protocol.ts";
export { layerChildProcess, layerTransport, type ChildProcessOptions } from "./connection.ts";
